# Generated by Django 3.1.4 on 2021-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfconverter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='file',
            name='file2',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
